### ISSUE TITLE
Add Tuto on Word2Vec ?

### ISSUE THREAD

**Issue by Lu7sodaa** [ujjwalkarn/Machine-Learning-Tutorials#21]
A quite good tuto on Word2Vec, just wanted to mention ! 
https://rare-technologies.com/word2vec-tutorial/
Thx for this repo !

**Comment by ujjwalkarn** [comment]
thanks! could you send a pull request?

**Comment by ujjwalkarn** [comment]
Since there was no reply, I added it myself. Thanks again for the suggestion!
